version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      # Use CONNECTION_STRING from .env file directly
      - CONNECTION_STRING=${CONNECTION_STRING:-mongodb://localhost:27017/easyway}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - PORT=5000
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"  # Now using port 3000 for nginx
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000  # Point to backend service name
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 